version: "3"
services:
  eureka:
    image: "dhananjay12/eureka-server:latest"
    environment:
      - "SPRING_EUREKA=http://eureka:8761/eureka"
    ports:
      - "8761:8761"
  gateway:
    image: "dhananjay12/fungible-gateway:latest"
    environment:
      - "JAVA_OPTS=-Djava.security.egd=file:/dev/./urandom"
      - "SPRING_PROFILES_ACTIVE=default,classical"
      - "SPRING_EUREKA=http://eureka:8761/eureka"
    ports:
      - "8050:8050"
  user:
    image: "dhananjay12/fungible-user-service:latest"
    environment:
      - "JAVA_OPTS=-Djava.security.egd=file:/dev/./urandom"
      - "SPRING_PROFILES_ACTIVE=default,classical"
      - "SPRING_EUREKA=http://eureka:8761/eureka"
    ports:
      - "8100:8100"
  contactus:
    image: "dhananjay12/fungible-contact-us-service:latest"
    environment:
      - "JAVA_OPTS=-Djava.security.egd=file:/dev/./urandom"
      - "SPRING_PROFILES_ACTIVE=default,classical"
      - "SPRING_EUREKA=http://eureka:8761/eureka"
    ports:
      - "8200:8200"

