server:
  port: 8050
  
#eureka:
#  client:
#    serviceUrl:
#      defaultZone: ${SPRING_EUREKA:http://localhost:8761/eureka/}

spring:
  cloud:
    gateway:
      discovery.locator:
        enabled: true
        lowerCaseServiceId: true
