server:
  port: 8050
  
#eureka:
#  client:
#    serviceUrl:
#      defaultZone: ${SPRING_EUREKA:http://localhost:8761/eureka/}

spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          url-expression: "'http://'+serviceId"
        x-forwarded:
          prefixEnabled: true
        kubernetes:
          reload:
            enabled: true
            mode: polling
            period: 5000
