server:
  port: 8050
  
#eureka:
#  client:
#    serviceUrl:
#      defaultZone: ${SPRING_EUREKA:http://localhost:8761/eureka/}

spring:
  application:
    name: gateway
  cloud:
    kubernetes:
      enabled: true
      reload:
        enabled: true
    gateway:
      discovery:
        locator:
          lowerCaseServiceId: true
          enabled: true

eureka:
  client:
    enabled: false

#spring:
#  cloud:
#    gateway:
#      discovery:
#        locator:
#          enabled: true
#          url-expression: "'http://'+serviceId"
#    kubernetes:
#      reload:
#        enabled: true
#        mode: polling
#        period: 5000
#      discovery:
#        filter: "metadata.labels['s1p']"

logging:
  level:
    root: DEBUG
    org.springframework.gateway: TRACE
    org.springframework.cloud.gateway: TRACE
    org.springframework.cloud.loadbalancer: TRACE


management:
  endpoints:
    web:
      exposure:
        include: '*'

