apiVersion: apps/v1
kind: Deployment
metadata:
  name: contact-us-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: contact-us-service
  template:
    metadata:
      labels:
        app: contact-us-service
    spec:
      containers:
      - env:
        - name: EUREKA_CLIENT_ENABLED
          value: "false"
        - name: SPRING_CLOUD_KUBERNETES_ENABLED
          value: "true"
        - name: SPRING_CLOUD_KUBERNETES_RELOAD_ENABLED
          value: "true"
        - name: SPRING_AUTOCONFIGURE_EXCLUDE
          value: "org.springframework.cloud.netflix.eureka.loadbalancer.LoadBalancerEurekaAutoConfiguration"
        image: dhananjay12/fungible-contact-us-service:master
        imagePullPolicy: Always
        name: contant-us-service
        resources:
          requests:
            memory: "256Mi"
          limits:
            memory: "512Mi"
        ports:
          - containerPort: 8080