apiVersion: v1
kind: Service
metadata:
  labels:
    name: gateway
  name: gateway
spec:
  type: LoadBalancer
  selector:
    app: gateway
  ports:
    - name: "gateway"
      port: 8080
      targetPort: 8080