apiVersion: v1
kind: Service
metadata:
  labels:
    name: user-service
  name: user-service
spec:
  type: ClusterIP
  selector:
    app: user-service
  ports:
    - port: 8100
      targetPort: 8080
      protocol: TCP