apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: zuul
spec:
  replicas: 1
  selector:
    matchLabels:
      component: zuul
  template:
    metadata:
      labels:
        component: zuul
    spec:
      containers:
        image: dhananjay12/fungible-zuul-server:latest
        name: zuul
        resources:
          requests:
            memory: "256Mi"
          limits:
            memory: "512Mi"
        ports:
        - containerPort: 8050
