server:
  port: 8100
  
#eureka:
#  client:
#    serviceUrl:
#      defaultZone: ${SPRING_EUREKA:http://localhost:8761/eureka/}
      

management:
  endpoints:
    web:
      exposure:
        include: '*'