server:
  port: 8200

    #eureka:
    #  client:
    #    serviceUrl:
    #      defaultZone: ${SPRING_EUREKA:http://localhost:8761/eureka/}


management:
  endpoints:
    web:
      exposure:
        include: '*'


spring:
  cloud:
    kubernetes:
      enabled: true
      reload:
        enabled: true
eureka:
  client:
    enabled: false